### ISSUE TITLE
review completed, 需要調整

### ISSUE THREAD

**Issue by hatelove** [WenpinLiao/TDDHomework-Day1#1]
11 筆資料，而不是 3 個集合或 4 個集合。
測試案例是用來描述需求的 context, scenario 的執行過程，以及預期的結果的。

也同時代表著，別人要怎麼用你設計的 production code API, 這個測試案例代表，要用我的 production code 前，請自己先把多個 group 資料準備好。而且還要使用一堆 Contact() 等 API 處理過，才能呼叫我。這也含著邏輯跟處理。

**Comment by MonkeyBinBin** [comment]
調整測試案例，把資料調整為11筆。也將不應該存在的邏輯跟處理移除。

**Comment by hatelove** [comment]
改得很好唷，這邊也先附上我的 sample 解答給你參考。
https://gist.github.com/hatelove/f5a4c2591293828b637f#file-getsumbypagesize_v2-cs

production code 的部分也可以參考一下，可以體會一下 LINQ to object 的美妙。
